export enum K8sStreamRequestTypeEnum {
  // Service *DEPRECATED*
  SERVICE__POD_LOG = 'SERVICE__POD_LOG',
  SERVICE__POD_EXEC_SH = 'SERVICE__POD_EXEC_SH',
  SERVICE__BUILD_LOG = 'SERVICE__BUILD_LOG',
  SERVICE__DEPLOYMENT_LOG = 'SERVICE__DEPLOYMENT_LOG',
  SERVICE__SCAN_IMAGE = 'SERVICE__SCAN_IMAGE',
  SERVICE__OPERATOR_LOG = 'SERVICE__OPERATOR_LOG',

  // Workspace
  WORKSPACE__CONTAINER_LOG = 'WORKSPACE__CONTAINER_LOG',
  WORKSPACE__CONTAINER_EXEC_SH = 'WORKSPACE__CONTAINER_EXEC_SH',
  WORKSPACE__EVENT_LOG = 'WORKSPACE__EVENT_LOG',
  WORKSPACE__OPERATOR_LOG = 'WORKSPACE__OPERATOR_LOG',
  WORKSPACE__HELM_OPERATOR_LOG = 'WORKSPACE__HELM_OPERATOR_LOG',

  //
  WORKSPACE__LIVE_STREAM_POD_TRAFFIC = 'WORKSPACE__LIVE_STREAM_POD_TRAFFIC',
  WORKSPACE__LIVE_STREAM_POD_CPU = 'WORKSPACE__LIVE_STREAM_POD_CPU',
  WORKSPACE__LIVE_STREAM_POD_MEMORY = 'WORKSPACE__LIVE_STREAM_POD_MEMORY',

  // Cluster
  CLUSTER__WORKLOAD = 'CLUSTER__WORKLOAD',
  // CLUSTER__TOOLS = 'CLUSTER__TOOLS',
  CLUSTER__OPERATOR_LOG = 'CLUSTER__OPERATOR_LOG',
  //
  CLUSTER__NODE_STREAM_NODES_TRAFFIC = 'CLUSTER__NODE_STREAM_NODES_TRAFFIC',
  CLUSTER__NODE_STREAM_NODES_CPU = 'CLUSTER__NODE_STREAM_NODES_CPU',
  CLUSTER__NODE_STREAM_NODES_MEMORY = 'CLUSTER__NODE_STREAM_NODES_MEMORY',

  K8S = 'k8s'
}
