export enum K8sSystemCheckEntryStatusEnum {
  UNKNOWN_STATUS = 'UNKNOWN_STATUS',
  INSTALLING = 'INSTALLING',
  UNINSTALLING = 'UNINSTALLING',
  NOT_INSTALLED = 'NOT_INSTALLED',
  INSTALLED = 'INSTALLED'
}
