# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  mo-agent-pool

resources:
  - repo: self

variables:
  SourceBranch: $(Build.SourceBranch)
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - script: |
              if [ "${RN:0:10}" = "refs/tags/" ]; then
                echo "Tag detected: ${RN:10}"
              fi
            displayName: 'check for tag'

          - script: |
              touch .npmrc
              echo "registry=https://pkgs.dev.azure.com/mogenius/_packaging/mogenius/npm/registry/" >> .npmrc
              echo "always-auth=true" >> .npmrc
            displayName: 'create .npmrc for auth task'

          - task: npmAuthenticate@0
            inputs:
              workingFile: '.npmrc'
            displayName: 'npm authenticate'

          - script: |
              npm ci
            displayName: 'Install dependencies'

          - script: |
              npm run build
            displayName: 'Build package'

          - script: |
              npm run semantic-release
            displayName: 'Semantic release'
