export const enum MoEventTopic {
  UNKNOWN = 'UNKOWN',
  DEPLOYMENT = 'DEPLOYMENT',
  BUILD = 'BUILD',
  REPOSITORY = 'REPOSITORY',
  INGRESS = 'INGRESS',
  CONTAINER = 'CONTAINER',
  STORAGE = 'STORAGE',
  INSTALL = 'INSTALL',
  SETUP = 'SETUP',
  MISC = 'MISC',
  INTERNAL = 'INTERNAL'
}
