export enum KubernetesWorkloadEnum {
  NAMESPACE = 'namespace',
  POD = 'pod',
  DEPLOYMENT = 'deployment',
  SERVICE = 'service',
  INGRESS = 'ingress',
  CONFIGMAP = 'configmap',
  SECRET = 'secret',
  NODE = 'node',
  DAEMON_SET = 'daemon_set',
  STATEFUL_SET = 'stateful_set',
  JOB = 'job',
  CRON_JOB = 'cron_job',
  REPLICA_SET = 'replica_set',
  PERSISTENT_VOLUME = 'persistent_volume',
  PERSISTENT_VOLUME_CLAIM = 'persistent_volume_claim',
  HORIZONTAL_POD_AUTOSCALER = 'horizontal_pod_autoscaler',
  EVENT = 'event',
  CERTIFICATE = 'certificate',
  CERTIFICATE_REQUEST = 'certificaterequest',
  ORDER = 'orders',
  ISSUER = 'issuer',
  CLUSTER_ISSUER = 'clusterissuer',
  SERVICE_ACCOUNT = "service_account",
  ROLE = "role",
  ROLE_BINDING = "role_binding",
  CLUSTER_ROLE = "cluster_role",
  CLUSTER_ROLE_BINDING = "cluster_role_binding",
  VOLUME_ATTACHMENT = "volume_attachment"
}

export const KubernetesWorkloadEnum_ALL = [
  KubernetesWorkloadEnum.NAMESPACE,
  KubernetesWorkloadEnum.POD,
  KubernetesWorkloadEnum.DEPLOYMENT,
  KubernetesWorkloadEnum.SERVICE,
  KubernetesWorkloadEnum.INGRESS,
  KubernetesWorkloadEnum.CONFIGMAP,
  KubernetesWorkloadEnum.SECRET,
  KubernetesWorkloadEnum.NODE,
  KubernetesWorkloadEnum.DAEMON_SET,
  KubernetesWorkloadEnum.STATEFUL_SET,
  KubernetesWorkloadEnum.REPLICA_SET,
  KubernetesWorkloadEnum.JOB,
  KubernetesWorkloadEnum.CRON_JOB,
  KubernetesWorkloadEnum.PERSISTENT_VOLUME,
  KubernetesWorkloadEnum.PERSISTENT_VOLUME_CLAIM,
  KubernetesWorkloadEnum.HORIZONTAL_POD_AUTOSCALER,
  KubernetesWorkloadEnum.EVENT,
  KubernetesWorkloadEnum.CERTIFICATE,
  KubernetesWorkloadEnum.CERTIFICATE_REQUEST,
  KubernetesWorkloadEnum.ORDER,
  KubernetesWorkloadEnum.ISSUER,
  KubernetesWorkloadEnum.CLUSTER_ISSUER,
  KubernetesWorkloadEnum.SERVICE_ACCOUNT,
  KubernetesWorkloadEnum.ROLE,
  KubernetesWorkloadEnum.ROLE_BINDING,
  KubernetesWorkloadEnum.CLUSTER_ROLE,
  KubernetesWorkloadEnum.CLUSTER_ROLE_BINDING,
  KubernetesWorkloadEnum.VOLUME_ATTACHMENT
];
