export enum AppLibraryTypeEnum {
  DOCKER = 'DOCKER',
  DOCKER_TEMPLATE = 'DOCKER_TEMPLATE',
  DOCKER_COMPOSE_TEMPLATE = 'DOCKER_COMPOSE_TEMPLATE',
  CONTAINER_IMAGE = 'CONTAINER_IMAGE'
}

export const AppLibraryTypeEnum_ALL = [
  AppLibraryTypeEnum.DOCKER,
  AppLibraryTypeEnum.DOCKER_TEMPLATE,
  AppLibraryTypeEnum.DOCKER_COMPOSE_TEMPLATE,
  AppLibraryTypeEnum.CONTAINER_IMAGE
];
