export enum PaymentSubscriptionPermissionsEnum {
  SUBSCRIPTION__OWNER = 'SUBSCRIPTION__OWNER',
  SUBSCRIPTION__ADMIN = 'SUBSCRIPTION__ADMIN',
  SUBSCRIPTION__USER = 'SUBSCRIPTION__USER',
  SUBSCRIPTION__VIEWER = 'SUBSCRIPTION__VIEWER'
}
