export enum SubscriptionStatusEnum {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  CANCELATION_PAYPAL_PENDING = 'CANCELATION_PAYPAL_PENDING',
  REFUNDED = 'REFUNDED',
  CANCELED = 'CANCELED',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
