export enum XtermRequestTypeEnum {
  // Service
  SERVICE__POD_LOG = 'SERVICE__POD_LOG',
  SERVICE__POD_EXEC_SH = 'SERVICE__POD_EXEC_SH',
  SERVICE__BUILD_LOG = 'SERVICE__BUILD_LOG',
  SERVICE__DEPLOYMENT_LOG = 'SERVICE__DEPLOYMENT_LOG',
  SERVICE__SCAN_IMAGE = 'SERVICE__SCAN_IMAGE',
  SERVICE__OPERATOR_LOG = 'SERVICE__OPERATOR_LOG',

  // Cluster
  CLUSTER__WORKLOAD = 'CLUSTER__WORKLOAD',
  // CLUSTER__TOOLS = 'CLUSTER__TOOLS',
  CLUSTER__OPERATOR_LOG = 'CLUSTER__OPERATOR_LOG',
  //
  CLUSTER__NODE_STREAM_NODES_TRAFFIC = 'CLUSTER__NODE_STREAM_NODES_TRAFFIC',
  CLUSTER__NODE_STREAM_NODES_CPU = 'CLUSTER__NODE_STREAM_NODES_CPU',
  CLUSTER__NODE_STREAM_NODES_MEMORY = 'CLUSTER__NODE_STREAM_NODES_MEMORY',

  K8S = 'k8s'
}
