export enum XtermRequestTypeEnum {
  SERVICE__POD_LOG = 'SERVICE__POD_LOG',
  SERVICE__POD_EXEC_SH = 'SERVICE__POD_EXEC_SH',
  SERVICE__BUILD_LOG = 'SERVICE__BUILD_LOG',
  SERVICE__DEPLOYMENT_LOG = 'SERVICE__DEPLOYMENT_LOG',
  SERVICE__SCAN_IMAGE = 'SERVICE__SCAN_IMAGE',
  CLUSTER__WORKLOAD = 'CLUSTER__WORKLOAD',
  CLUSTER__TOOLS = 'CLUSTER__TOOLS',
  K8S = 'k8s'
}
