export enum UserSocketDataEventEnum {
  GET_USER = 'GET_USER',
  EMAIL_VALIDATED = 'EMAIL_VALIDATED',
  PHONE_NUMBER_VALIDATED = 'PHONE_NUMBER_VALIDATED',
  LOGOUT = 'LOGOUT',
  GET_NOTIFICATION_LIST = 'GET_NOTIFICATION_LIST'
}
