export enum KubernetesEventStatusReasonEnum {
  SUCCESSFUL_CREATE = 'SuccessfulCreate',
  SUCCESSFUL_DELETE = 'SuccessfulDelete',
  SCHEDULED = 'Scheduled',
  KILLING = 'Killing',
  EVICTED = 'Evicted',
  EXCEEDED_GRACE_PERIOD = 'ExceededGracePeriod',
  FAILED_KILL_POD = 'FailedKillPod',
  FAILED = 'Failed',
  PULLING = 'Pulling',
  PULLED = 'Pulled',
  CREATED = 'Created',
  STARTED = 'Started',
  BACK_OFF = 'BackOff',
  POD_SCHEDULED = 'PodScheduled',
  SUCCESSFUL_ASSIGN = 'SuccessfulAssign',
  FAILED_CREATE = 'FailedCreate',
  FAILED_DELETE = 'FailedDelete',
  FAILED_MOUNT = 'FailedMount',
  FAILED_SCHEDULING = 'FailedScheduling',
  FAILED_VALIDATION = 'FailedValidation'
}
