export enum SubscriptionStateEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  INACTIVE_BANNED = 'INACTIVE_BANNED',
  INACTIVE_PAYMENT = 'INACTIVE_PAYMENT',
  INACTIVE_SUSPENDED = 'INACTIVE_SUSPENDED'
}
