export enum ProjectSocketDataEventEnum {
  GET_PROJECT = 'GET_PROJECT',
  GET_PROJECT_LIST = 'GET_PROJECT_LIST',

  GET_PROJECT_NAMESPACE_LIST = 'GET_PROJECT_NAMESPACE_LIST',
  GET_PROJECT_NAMESPACE = 'GET_PROJECT_NAMESPACE',
  GET_PROJECT_NAMESPACE_TRAFFIC = 'GET_PROJECT_NAMESPACE_TRAFFIC',

  GET_PROJECT_NAMESPACE_SERVICE = 'GET_PROJECT_NAMESPACE_SERVICE',
  GET_PROJECT_NAMESPACE_SERVICE_LIST = 'GET_PROJECT_NAMESPACE_SERVICE_LIST',
  // UPDATE_PROJECT_SERVICE_STATE = 'UPDATE_PROJECT_SERVICE_STATE',

  GET_PROJECT_USER_LIST = 'GET_PROJECT_USER_LIST',

  UPDATE_PROJECT_NAMESPACE_SERVICE_STATE = 'UPDATE_PROJECT_NAMESPACE_SERVICE_STATE',
  UPDATE_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD_STATE = 'UPDATE_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD_STATE',
}
