export enum ProjectSocketDataEventEnum {
  GET_PROJECT = 'GET_PROJECT',
  GET_PROJECT_LIST = 'GET_PROJECT_LIST',

  GET_PROJECT_NAMESPACE_LIST = 'GET_PROJECT_NAMESPACE_LIST',
  GET_PROJECT_NAMESPACE = 'GET_PROJECT_NAMESPACE',
  GET_PROJECT_NAMESPACE_TRAFFIC = 'GET_PROJECT_NAMESPACE_TRAFFIC',

  GET_PROJECT_NAMESPACE_SERVICE = 'GET_PROJECT_NAMESPACE_SERVICE',
  GET_PROJECT_NAMESPACE_SERVICE_LIST = 'GET_PROJECT_NAMESPACE_SERVICE_LIST',
  // UPDATE_PROJECT_SERVICE_STATE = 'UPDATE_PROJECT_SERVICE_STATE',

  GET_PROJECT_USER_LIST = 'GET_PROJECT_USER_LIST',

  // project namespace service
  UPDATE_PROJECT_NAMESPACE_SERVICE_STATE = 'UPDATE_PROJECT_NAMESPACE_SERVICE_STATE',
  UPDATE_PROJECT_NAMESPACE_SERVICE_STATUS = 'UPDATE_PROJECT_NAMESPACE_SERVICE_STATUS',
  UPDATE_PROJECT_NAMESPACE_SERVICE_CRONJOB_JOB_LIST = 'UPDATE_PROJECT_NAMESPACE_SERVICE_CRONJOB_JOB_LIST',
  UPDATE_PROJECT_NAMESPACE_SERVICE_MESSAGES = 'UPDATE_PROJECT_NAMESPACE_SERVICE_MESSAGES',

  // project namespace service container pod
  CREATED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD = 'CREATED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD',
  DELETED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD = 'DELETED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD',
  UPDATED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD_STATE = 'UPDATED_PROJECT_NAMESPACE_SERVICE_CONTAINER_POD_STATE'
}
