export enum PaypalTypesEnum {
  BILLING_SUBSCRIPTION_CREATED = 'BILLING.SUBSCRIPTION.CREATED',
  BILLING_SUBSCRIPTION_CANCELLED = 'BILLING.SUBSCRIPTION.CANCELLED',
  BILLING_SUBSCRIPTION_ACTIVATED = 'BILLING.SUBSCRIPTION.ACTIVATED',
  BILLING_SUBSCRIPTION_SUSPENDED = 'BILLING.SUBSCRIPTION.SUSPENDED',
  BILLING_SUBSCRIPTION_PAYMENT_FAILED = 'BILLING.SUBSCRIPTION.PAYMENT.FAILED',
  BILLING_PLAN_CREATED = 'BILLING.PLAN.CREATED',
  PAYMENT_SALE_COMPLETED = 'PAYMENT.SALE.COMPLETED'
}

export const PaypalTypesEnum_ALL = [
  PaypalTypesEnum.BILLING_SUBSCRIPTION_CREATED,
  PaypalTypesEnum.BILLING_SUBSCRIPTION_CANCELLED,
  PaypalTypesEnum.BILLING_SUBSCRIPTION_ACTIVATED,
  PaypalTypesEnum.BILLING_SUBSCRIPTION_SUSPENDED,
  PaypalTypesEnum.BILLING_SUBSCRIPTION_PAYMENT_FAILED,
  PaypalTypesEnum.BILLING_PLAN_CREATED,
  PaypalTypesEnum.PAYMENT_SALE_COMPLETED
];
