export enum ServiceLibraryPermissionsEnum {
  SERVICE_LIBRARY__ADMIN = 'SERVICE_LIBRARY__ADMIN',
  SERVICE_LIBRARY__USER = 'SERVICE_LIBRARY__USER',
  SERVICE_LIBRARY__VIEWER = 'SERVICE_LIBRARY__VIEWER'
}
