export enum SubscriptionPoolPermissionsEnum {
  SUBSCRIPTION_POOL__OWNER = 'SUBSCRIPTION_POOL__OWNER',
  SUBSCRIPTION_POOL__ADMIN = 'SUBSCRIPTION_POOL__ADMIN',
  SUBSCRIPTION_POOL__USER = 'SUBSCRIPTION_POOL__USER',
  SUBSCRIPTION_POOL__VIEWER = 'SUBSCRIPTION_POOL__VIEWER'
}
