export enum NamespaceSocketDataEventEnum {
  GET_NAMESPACE = 'GET_NAMESPACE',
  GET_NAMESPACE_LIST = 'GET_NAMESPACE_LIST',
  GET_NAMESPACE_STAGE_LIST = 'GET_NAMESPACE_STAGE_LIST',
  GET_NAMESPACE_STAGE = 'GET_NAMESPACE_STAGE',
  GET_NAMESPACE_SERVICE = 'GET_NAMESPACE_SERVICE',
  GET_NAMESPACE_SERVICE_LIST = 'GET_NAMESPACE_SERVICE_LIST',
  GET_NAMESPACE_USER_LIST = 'GET_NAMESPACE_USER_LIST'
}
