export enum NamespaceSocketDataEventEnum2 {
  GET_NAMESPACE = 'GET_NAMESPACE',
  GET_NAMESPACE_LIST = 'GET_NAMESPACE_LIST',
  GET_NAMESPACE_STAGE_LIST = 'GET_NAMESPACE_STAGE_LIST',
  GET_NAMESPACE_STAGE = 'GET_NAMESPACE_STAGE',

  GET_NAMESPACE_SERVICE = 'GET_NAMESPACE_SERVICE',
  GET_NAMESPACE_SERVICE_LIST = 'GET_NAMESPACE_SERVICE_LIST',
  // UPDATE_NAMESPACE_SERVICE_STATE = 'UPDATE_NAMESPACE_SERVICE_STATE',

  GET_NAMESPACE_USER_LIST = 'GET_NAMESPACE_USER_LIST'
}
