export enum UserSocketDataEventEnum {
  GET_USER = 'GET_USER',
  GET_USER_SILENT = 'GET_USER_SILENT',
  EMAIL_VALIDATED = 'EMAIL_VALIDATED',
  PHONE_NUMBER_VALIDATED = 'PHONE_NUMBER_VALIDATED',
  LOGOUT = 'LOGOUT',
}
