export enum ProductOrganizationSocketDataEventEnum {
  GET_SENT_ORGANIZATION_INVITATION_LIST = 'GET_SENT_ORGANIZATION_INVITATION_LIST',
  GET_RECEIVED_ORGANIZATION_INVITATION_LIST = 'GET_RECEIVED_ORGANIZATION_INVITATION_LIST'
}
