export enum ProductClusterSocketDataEventEnum {
  //
  CLUSTER_CONNECTION_STATUS = 'CLUSTER_CONNECTION_STATUS',
  CLUSTER_UPDATED = 'CLUSTER_UPDATED',
  CLUSTER_NETWORK_POLICY_UPDATED = 'CLUSTER_NETWORK_POLICY_UPDATED',
  CLUSTER_WORKSPACE_STORAGE_VOLUMNE_EVENTS = 'CLUSTER_WORKSPACE_STORAGE_VOLUMNE_EVENTS',
  CLUSTER_WORKSPACE_STORAGE_FILE_EVENTS = 'CLUSTER_WORKSPACE_STORAGE_FILE_EVENTS',
  CLUSTER_WORKSPACE_STORAGE_STATUS_EVENTS = 'CLUSTER_WORKSPACE_STORAGE_STATUS_EVENTS'
}
