export enum ProductOrganizationSocketDataEventEnum {
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  GET_ORGANIZATION_INVITATION_LIST = 'GET_ORGANIZATION_INVITATION_LIST',
  GET_ORGANIZATION_MEMBER_LIST = 'GET_ORGANIZATION_MEMBER_LIST',
}
