export enum ProductOrganizationSocketDataEventEnum {
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  GET_ORGANIZATION_INVITATION_LIST = 'GET_ORGANIZATION_INVITATION_LIST',
  GET_ORGANIZATION_MEMBER_LIST = 'GET_ORGANIZATION_MEMBER_LIST'
}
