export enum ProductClusterSocketDataEventEnum {
  CLUSTER_CONNECTION_STATUS = 'CLUSTER_CONNECTION_STATUS',
  CLUSTER_UPDATED = 'CLUSTER_UPDATED',
  CLUSTER_NETWORK_POLICY_UPDATED = 'CLUSTER_NETWORK_POLICY_UPDATED'
}
