export enum NamespaceSocketEventEnum {
  NAMESPACE_COMMAND_SERVICE = 'NAMESPACE_COMMAND_SERVICE',
  NAMESPACE_INVITATION_SERVICE = 'NAMESPACE_INVITATION_SERVICE',
  NAMESPACE_SERVICE = 'NAMESPACE_SERVICE'
}
