name: Node.js Publish Pkg

on:
  push:
    branches:
      - main
      - develop

jobs:
  publish-gpr:
    runs-on: [self-hosted-ansible]
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with: 
          clean: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Release new pkg from main
        run: npm run semantic-release